config/routes.rb
Rails.application.routes.draw do

  
  scope "(:locale)", locale: /es|en/ do
    devise_for :users
      resources :pins do
        member do
          put "like", to: "pins#upvote"
      end
    end
  root "pins#index"
  end

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	acts_as_votable
	belongs_to :user

	has_attached_file :image, styles: { medium: "300x300>" }
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
	validates :title, presence:true 

	def self.search(search)
  		where("title LIKE ?", "%#{search}%")
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  	
  	before_action :set_locale

  	def set_locale
  		I18n.locale = params[:locale] || I18n.default_locale
	end

	def default_url_options(options={})
  		{ locale: I18n.locale }
	end

end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
	before_action :find_pin, only: [:show, :edit, :update, :destroy, :upvote]
	before_action :authenticate_user!, except: [:index, :show]

	add_breadcrumb I18n.t("layouts.application.title"), :root_path

	def index
		#@pins = Pin.all.order("created_at DESC")
		if params[:search]
			@pins = Pin.search(params[:search]).order("created_at DESC")
		else
			@pins = Pin.all.order("created_at DESC")
		end
	end

	def new
		@pin = current_user.pins.build
		add_breadcrumb I18n.t("layouts.application.newPin")
	end

	def create
		@pin = current_user.pins.build(pin_params)

		if @pin.save
			redirect_to @pin, notice: "Pin creado correctamente"
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @pin.update(pin_params)
			redirect_to @pin, notice: "Pin modificado correctamente"			
		else
			render 'edit'
		end
	end

	def destroy
		@pin.destroy
		redirect_to root_path
	end

	def upvote
		@pin.upvote_by current_user
		redirect_to :back
	end

	private

	def pin_params
		params.require(:pin).permit(:title, :description, :image)
	end

	def find_pin
		@pin = Pin.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  # A simple way to show error messages for the current devise resource. If you need
  # to customize this method, you can either overwrite it in your application helpers or
  # copy the views to your application.
  #
  # This method is intended to stay simple and it is unlikely that we are going to change
  # it to add more behavior or options.
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:div, msg) }.join

    html = <<-HTML
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span></button>
        #{messages}
      </div>
    HTML

    html.html_safe
  end
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.haml
!!!5
%html
%head
	%title= t 'layouts.application.title'
	=stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true 
	=javascript_include_tag 'application', 'data-turbolinks-track' => true 
	=csrf_meta_tags 
%body
	%nav.navbar.navbar-default
		.container
			.navbar-brand= link_to I18n.t('layouts.application.title'), root_path
			%ul.nav.navbar-nav.navbar-right

				%li.dropdown
					%a.dropdown-toggle{:href => "#", "role" => "button", "data-toggle" => "dropdown", "data-target" => "#"}
						= I18n.t('layouts.application.language')
						%span.caret
					%ul.dropdown-menu{"role" => "menu"}
						%li= link_to ('ES'), request.env['PATH_INFO'].sub('en','es')
						%li= link_to ('EN'), request.env['PATH_INFO'].sub('es','en')
			-if user_signed_in?
				%ul.nav.navbar-nav.navbar-right
					%li= link_to I18n.t('layouts.application.newPin'), new_pin_path
					%li= link_to I18n.t('layouts.application.account'), edit_user_registration_path
					%li= link_to I18n.t('layouts.application.signOut'), destroy_user_session_path, method: :delete
			-else
				%ul.nav.navbar-nav.navbar-right
					%li= link_to I18n.t('layouts.application.signUp'), new_user_registration_path
					%li= link_to I18n.t('layouts.application.signIn'), new_user_session_path
			
			= form_tag pins_path, :method => 'get', class: 'navbar-form navbar-center' do
				.form-group.has-error
					= text_field_tag :search, nil, class: 'form-control'
					= submit_tag 'Buscar', :name => nil, class: 'btn btn-default'
	.container
		-flash.each do |type, msg|
			-if type == 'alert' 
				.alert.alert-danger.alert-dismissible{:role => "alert"}
					%button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
						%span{"aria-hidden" => "true"} &times; 
					=msg
		-if request.env['PATH_INFO'] != '/es' and request.env['PATH_INFO'] != '/en'
			.row
				%ol.breadcrumb
					=render_breadcrumbs :tag => :li, :separator => ""
		=yield

app/views/pins/_form.html.haml
= simple_form_for @pin, html: {multipart: true} do |f|
	- if @pin.errors.any?
		#errors
			%h2
			=pluralize(@pin.errors.count, "error")
			prevented this Pin from saving
			%ul
				-@pin.errors.full_messages do |msg|
					%li=msg

	.form-group
		=f.file_field :image, input_html:{class: 'btn btn-default'}
	.form-group
		= f.input :title, input_html:{class: 'form-control'}
	.form-group
		= f.input :description,  input_html:{class: 'form-control'}
	=f.button :submit,  class: "btn btn-primary"

app/views/pins/edit.html.haml
.col-md-6.col-md-offset-3
	.panel.panel-default
		.panel-heading
			.panel-header
				%h1 Edit
		.panel-body
			= image_tag @pin.image.url(:medium)
			= render 'form'

app/views/pins/index.html.haml
#pins.transitions-enabled 
	- @pins.each do |pin|
		.box.panel.panel-default
			= link_to (image_tag pin.image.url()), pin
			.panel-body
				%h2= link_to pin.title, pin
				%p.user
					= t 'pins.index.uploadedBy'
					= pin.user.email

app/views/pins/new.html.haml
.col-md-6.col-md-offset-3
	.row
		.panel.panel-deafult
			.panel-heading
				%h1 Nuevo Pin
			.panel-body
				= render 'form'

app/views/pins/show.html.haml
#pin_show.row
	.col-md-8.col-md-offset-2
		.panel.panel-default
			.panel-heading.pin_image
				= image_tag @pin.image.url()
			.panel-body
				%h1= @pin.title
				%p.description= @pin.description
			.panel-footer
				.row
					.col-md-6
						%p.user
							= t 'pins.index.uploadedBy'
							= @pin.user.email
					.col-md-6
						.btn-group.pull-right
							= link_to like_pin_path(@pin), method: :put, class: "btn btn-default" do
								%span.glyphicon.glyphicon-heart
									= @pin.get_upvotes.size
							- if user_signed_in?
								= link_to "Edit", edit_pin_path, class: "btn btn-default"
								= link_to "Delete", pin_path, method: :delete, data: { confirm: "Estas seguro?" }, class: "btn btn-default"